anguage: generic

cache:
  directories:
    # General SwiftPM
    - .build
    # XCodebuild cache
    - build

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      install:
        - gem install bundler
        - bundle install
        - npm install -g danger
      script:
        - swift package generate-xcodeproj
        - xcodebuild test -scheme DangerSwiftCoverage-Package -derivedDataPath build/ -enableCodeCoverage YES | XCPRETTY_JSON_FILE_OUTPUT=result.json xcpretty -f `xcpretty-json-formatter`
        - DEBUG="*" swift run danger-swift ci
        
    - os: osx
      osx_image: xcode11.3
      install:
        - gem install bundler
        - bundle install
        - npm install -g danger
      script:
        - swift test --enable-code-coverage=true
        - DEBUG="*" swift run danger-swift ci --id spmCoverage --dangerfile SPMDangerfile.swift
        
    - os: osx
      osx_image: xcode11.3
      install:
        - gem install bundler
        - bundle install
        - npm install -g danger
      script:
        - swift package generate-xcodeproj
        - xcodebuild test -scheme DangerSwiftCoverage-Package -derivedDataPath build/ -resultBundlePath build/results -enableCodeCoverage YES
        - DEBUG="*" swift run danger-swift ci --id customPath --dangerfile CustomPath.swift
        
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - gem install bundler
        - bundle install
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 5.1
        - npm install -g danger
      script:
        - swift test --enable-code-coverage=true
        - DEBUG="*" swift run danger-swift ci --id spmCoverage --dangerfile SPMDangerfile.swift
